# Generated by Django 4.0.5 on 2022-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_salepost_image1_alter_salepost_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepost',
            name='image1',
            field=models.ImageField(blank=True, default='media/views/default.png', null=True, upload_to='media/views'),
        ),
        migrations.AlterField(
            model_name='salepost',
            name='image2',
            field=models.ImageField(blank=True, default='media/views/default.png', null=True, upload_to='media/views'),
        ),
        migrations.AlterField(
            model_name='salepost',
            name='image3',
            field=models.ImageField(blank=True, default='media/views/default.png', null=True, upload_to='media/views'),
        ),
    ]
